config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cart_items, only: [:create, :destroy]
  resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
        helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(
      name: params[:product][:name],
      price: params[:product][:price])
    if @product.save
      flash[:info] = "商品を登録しました"
      redirect_to products_path
    else
      @product.pass = ""
      render :new
    end
  end 
  
  def destroy
    product = Product.find(params[:id])
    product.destroy
    flash[:info] = "商品を削除しました"
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SWEXEL7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>

<% if flash[:info] %>
  <font color="green"><%= flash[:info] %></font>
<% end %>

<% @products.each do |e| %>
  <p>
      <%= e.name %>
      <%= link_to '削除', product_path(e), method: :delete %>
  </p>
<% end %>

<hr>

<%= link_to '商品追加', new_product_path %>

app/views/products/new.html.erb
<h1>商品登録</h1>

<% if @product.errors.present? %>
<font color="red">
    <h3>エラーがあります</h3>
    <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
    </font>
<% end %>

<%= form_for @product, url: {action: :create} do |f| %>
<p>  
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %></p>
<p>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %></p>
<p>
    <%= f.submit '登録' %>
</p>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>